"""Stronger, higher-variability drop-in replacements for two pieces of the
default Smashcima handwritten pipeline:

- `WavyStafflinesSynthesizer`: like `NaiveStafflinesSynthesizer`, but each
  staffline gets its own randomized stroke width (varying along its length,
  not just a fixed rectangle) and a gentle non-straight wobble, so lines
  don't look ruler-drawn.
- `StrongHandwrittenPostprocessor`: like `BaseHandwrittenPostprocessor`, but
  adds Kanungo-style foreground/background noise, foreground
  dilation/erosion, extra background noise and stray background text, an
  extra full-page affine jitter, and a small independent ink-layer jitter.
  The extra ink/paper filters specifically take advantage of the fact that
  ink, stafflines and paper are still separate layers at this stage of the
  pipeline - something a flattened image could not exploit. Every filter
  that warps geometry (rotation, the affine jitter, the ink-layer jitter)
  also keeps a caller-provided list of glyph bounding boxes in sync, so
  they stay correct after augmentation; its own `Folding` (paper-fold) is
  disabled since that particular warp can't be tracked precisely enough.

Both classes are meant to be wired into a `MppModel`-style orchestration
model in place of the stock Smashcima services (see
`generate_smashcima_dataset_strong.py`).
"""

import random
import sys
from typing import List, Tuple

import cv2
import numpy as np

import smashcima as sc
from smashcima.exporting.image.ImageLayer import ImageLayer
from smashcima.exporting.image.LayerSet import LayerSet
from smashcima.exporting.postprocessing.BaseHandwrittenPostprocessor import (
    BaseHandwrittenPostprocessor,
)
from smashcima.exporting.postprocessing.Filter import Filter
from smashcima.exporting.postprocessing.FilterStack import FilterStack
from smashcima.geometry.units import mm_to_px
from smashcima.synthesis.page.NaiveStafflinesSynthesizer import (
    NaiveStafflinesSynthesizer,
)


# =============================================================================
# Stafflines: variable stroke width + gentle waviness
# =============================================================================


class WavyStafflinesSynthesizer(NaiveStafflinesSynthesizer):
    """Draws stafflines as rasterized, hand-drawn-looking strokes instead of
    perfectly straight, uniform-width rectangles.

    Each staffline independently gets:
    - a random overall stroke width (so lines within a staff, and staves
      across a page, are not all identically thick), and
    - a small amount of low-frequency waviness and thickness wobble along
      its length, generated by interpolating a handful of random control
      points (so the line "breathes" like a real pen stroke would, without
      becoming jagged).
    """

    def __init__(
        self,
        rng: random.Random,
        thickness_range: Tuple[float, float] = (0.6, 1.6),
        waviness_range_mm: Tuple[float, float] = (0.0, 0.20),
        thickness_wobble_fraction: float = 0.5,
    ) -> None:
        super().__init__()
        self.rng = rng
        self.thickness_range = thickness_range
        self.waviness_range_mm = waviness_range_mm
        self.thickness_wobble_fraction = thickness_wobble_fraction

    def create_staff_glyph(
        self,
        staff_space: "sc.AffineSpace",
        width: float,
    ) -> "sc.ComposedGlyph":
        sub_glyphs: List["sc.Glyph"] = []

        for line_offset in range(-2, 3):
            base_y = line_offset * self.staff_space_unit
            sub_glyphs.append(self._make_wavy_line_glyph(width, base_y))

        composed_glyph = sc.ComposedGlyph.build(
            label=sc.SmashcimaLabels.staff.value,
            sub_glyphs=sub_glyphs,
        )
        composed_glyph.space.parent_space = staff_space

        return composed_glyph

    def _make_wavy_line_glyph(self, width: float, base_y: float) -> "sc.Glyph":
        dpi = 300
        rng = self.rng

        line_thickness_mm = self.line_thickness * rng.uniform(*self.thickness_range)
        waviness_amp_mm = rng.uniform(*self.waviness_range_mm)
        thickness_wobble_mm = (
            line_thickness_mm * rng.uniform(0.0, self.thickness_wobble_fraction)
        )

        pixel_width = max(int(mm_to_px(width, dpi=dpi)), 1)

        # enough vertical padding to fit the thickest/most-wobbly variant
        half_extent_mm = (
            line_thickness_mm / 2 + thickness_wobble_mm / 2 + waviness_amp_mm + 0.15
        )
        pixel_half_extent = max(int(mm_to_px(half_extent_mm, dpi=dpi)), 2)
        pixel_height = pixel_half_extent * 2

        # a handful of random control points, interpolated across the width,
        # gives a smooth (not jagged) wobble in both position and thickness
        n_ctrl = max(4, pixel_width // 60 + 2)
        xs_ctrl = np.linspace(0, pixel_width - 1, n_ctrl)
        y_ctrl = [rng.gauss(0.0, waviness_amp_mm) for _ in range(n_ctrl)]
        t_ctrl = [rng.gauss(0.0, thickness_wobble_mm / 2) for _ in range(n_ctrl)]

        xs = np.arange(pixel_width)
        center_offset_mm = np.interp(xs, xs_ctrl, y_ctrl)
        thickness_delta_mm = np.interp(xs, xs_ctrl, t_ctrl)

        # mm_to_px() only accepts scalars, so convert the per-column arrays
        # by hand using the px-per-mm ratio at this DPI
        px_per_mm = mm_to_px(1.0, dpi=dpi)
        center_px = pixel_half_extent + center_offset_mm * px_per_mm
        half_thickness_px = np.clip(
            (line_thickness_mm / 2 + thickness_delta_mm) * px_per_mm,
            1.0,
            None,
        )

        top = np.clip(
            np.floor(center_px - half_thickness_px), 0, pixel_height - 1
        ).astype(int)
        bottom = np.clip(
            np.ceil(center_px + half_thickness_px), 0, pixel_height - 1
        ).astype(int)

        bitmap = np.zeros((pixel_height, pixel_width, 4), dtype=np.uint8)
        rows = np.arange(pixel_height)[:, np.newaxis]
        mask = (rows >= top[np.newaxis, :]) & (rows <= bottom[np.newaxis, :])
        bitmap[mask] = self.line_color

        line_space = sc.AffineSpace()
        sprite = sc.Sprite(
            space=line_space,
            bitmap=bitmap,
            bitmap_origin=sc.Point(0.5, 0.5),
            dpi=dpi,
        )
        sprite.transform = sc.Transform.translate(sc.Vector2(width / 2, base_y))

        # extracting the region from the actual rasterized alpha channel
        # (rather than assuming a rectangle) keeps the staffline bounding
        # box accurate despite the waviness/thickness variation
        region = sc.Glyph.build_region_from_sprites_alpha_channel(
            label=sc.SmashcimaLabels.staffLine.value,
            sprites=[sprite],
        )

        return sc.Glyph(space=line_space, region=region, sprites=[sprite])


# =============================================================================
# Postprocessing filters
# =============================================================================


class _KanungoNoise(Filter):
    """Kanungo et al. (1993) style document-degradation noise, applied
    directly to the ink layer's foreground/background alpha mask: isolated
    foreground pixels get randomly erased near the ink boundary and isolated
    background pixels get randomly turned into ink, with a probability that
    decays with distance from the boundary. This is only meaningful because
    the ink layer still carries a clean foreground/background split at this
    point in the pipeline."""

    def apply_to(self, input: ImageLayer) -> ImageLayer:
        alpha = input.bitmap[:, :, 3]
        bgr = input.bitmap[:, :, 0:3]

        fg = (alpha > 127).astype(np.uint8)
        bg = 1 - fg

        dist_fg = cv2.distanceTransform(fg * 255, cv2.DIST_L2, 5)
        dist_bg = cv2.distanceTransform(bg * 255, cv2.DIST_L2, 5)

        a0 = self.rng.uniform(0.2, 0.6)
        alpha_decay = self.rng.uniform(0.5, 2.0)
        b0 = self.rng.uniform(0.05, 0.2)
        beta_decay = self.rng.uniform(1.0, 4.0)

        p_fg_to_bg = a0 * np.exp(-alpha_decay * dist_fg**2)
        p_bg_to_fg = b0 * np.exp(-beta_decay * dist_bg**2)

        rand_state = np.random.RandomState(self.rng.randint(0, 2**31 - 1))
        rand_fg = rand_state.random_sample(alpha.shape)
        rand_bg = rand_state.random_sample(alpha.shape)

        new_fg = fg.copy()
        new_fg[(fg == 1) & (rand_fg < p_fg_to_bg)] = 0
        new_fg[(bg == 1) & (rand_bg < p_bg_to_fg)] = 1

        # a tiny random closing removes single-pixel salt speckle, matching
        # the morphological cleanup step of the original Kanungo model
        k = self.rng.choice([1, 2])
        if k > 1:
            kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (k, k))
            new_fg = cv2.morphologyEx(new_fg, cv2.MORPH_CLOSE, kernel)

        new_alpha = (new_fg * 255).astype(np.uint8)
        bitmap = np.concat([bgr, new_alpha[:, :, np.newaxis]], axis=2)

        return ImageLayer(
            bitmap=bitmap, dpi=input.dpi, space=input.space, regions=input.regions
        )


class _ForegroundMorphology(Filter):
    """Randomly dilates or erodes the ink foreground with a kernel size
    sampled from `kernel_range`, simulating scanner/photocopier ink spread
    or thinning. Meant to be instantiated twice with different
    (probability, kernel_range) tiers: a frequent small-kernel jitter and a
    rarer, stronger large-kernel jitter."""

    def __init__(
        self,
        rng: random.Random,
        p: float,
        kernel_range: Tuple[int, int],
    ) -> None:
        super().__init__(rng, p)
        self.kernel_range = kernel_range

    def apply_to(self, input: ImageLayer) -> ImageLayer:
        bgr = input.bitmap[:, :, 0:3]
        alpha = input.bitmap[:, :, 3]

        ksize = self.rng.randint(*self.kernel_range)
        kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (ksize, ksize))

        if self.rng.random() < 0.5:
            alpha = cv2.dilate(alpha, kernel)
            bgr = 255 - cv2.dilate(255 - bgr, kernel)
        else:
            alpha = cv2.erode(alpha, kernel)
            bgr = 255 - cv2.erode(255 - bgr, kernel)

        bitmap = np.concat([bgr, alpha[:, :, np.newaxis]], axis=2)

        return ImageLayer(
            bitmap=bitmap, dpi=input.dpi, space=input.space, regions=input.regions
        )


PointList = List[Tuple[float, float]]
"""A single tracked item: a small list of (x, y) points. The caller decides
what the points mean - e.g. 4 corners of a glyph's bbox (collapsed back into
an axis-aligned box once all transforms are done) or the 2 endpoints of a
staffline's centerline (kept as a line segment, never collapsed - an
axis-aligned box around a rotated line balloons badly, since a long thin
rectangle's true rotated bbox is a much taller parallelogram)."""


def _translate_points(point_lists: List[PointList], dx: float, dy: float) -> None:
    """Translates every point of every tracked item in place."""
    for points in point_lists:
        for i, (x, y) in enumerate(points):
            points[i] = (x + dx, y + dy)


def _affine_transform_points(
    point_lists: List[PointList], matrix: np.ndarray
) -> None:
    """Applies a 2x3 affine matrix to every point of every tracked item, in
    place."""
    for points in point_lists:
        for i, (x, y) in enumerate(points):
            points[i] = (
                float(matrix[0, 0] * x + matrix[0, 1] * y + matrix[0, 2]),
                float(matrix[1, 0] * x + matrix[1, 1] * y + matrix[1, 2]),
            )


def _rotate_points(
    point_lists: List[PointList],
    cx: float,
    cy: float,
    x_offset: float,
    y_offset: float,
    angle: float,
) -> None:
    """Rotates every point of every tracked item in place around (cx, cy) by
    `angle` degrees, then shifts by (x_offset, y_offset) - the same
    convention `rotate_point` in `augraphy.augmentations.lib` uses for
    Augraphy's own rotation filters."""
    from augraphy.augmentations.lib import rotate_point

    for points in point_lists:
        for i, (x, y) in enumerate(points):
            rx, ry = rotate_point(x, y, cx, cy, angle)
            points[i] = (rx + x_offset, ry + y_offset)


class _InkLayerJitter(Filter):
    """Nudges only the ink layer by a small random translation, relative to
    the stafflines and paper layers, simulating handwriting that is not
    perfectly aligned with the printed staff. Only possible because ink is
    still a separate layer at this point, independent from the stafflines
    and paper layers it will later be merged with."""

    def __init__(
        self,
        rng: random.Random,
        p: float,
        postprocessor: "StrongHandwrittenPostprocessor",
    ) -> None:
        super().__init__(rng, p)
        self.postprocessor = postprocessor

    def apply_to(self, input: ImageLayer) -> ImageLayer:
        h, w = input.bitmap.shape[:2]
        dx = self.rng.uniform(-0.01, 0.01) * w
        dy = self.rng.uniform(-0.01, 0.01) * h

        matrix = np.array([[1, 0, dx], [0, 1, dy]], dtype=np.float32)
        bitmap = cv2.warpAffine(
            input.bitmap,
            matrix,
            (w, h),
            flags=cv2.INTER_LINEAR,
            borderMode=cv2.BORDER_CONSTANT,
            borderValue=(0, 0, 0, 0),
        )

        _translate_points(self.postprocessor.tracked_ink_points, dx, dy)

        return ImageLayer(
            bitmap=bitmap, dpi=input.dpi, space=input.space, regions=input.regions
        )


class _PaperNoise(Filter):
    """Adds extra scan/sensor-style noise to the paper (background) layer."""

    def apply_to(self, input: ImageLayer) -> ImageLayer:
        import albumentations as A

        bgr = input.bitmap[:, :, 0:3]

        transform = A.Compose(
            [
                A.OneOf(
                    [
                        A.GaussNoise(std_range=(0.02, 0.12), p=1.0),
                        A.ISONoise(
                            color_shift=(0.01, 0.05), intensity=(0.1, 0.6), p=1.0
                        ),
                        A.MultiplicativeNoise(
                            multiplier=(0.85, 1.15), per_channel=True, p=1.0
                        ),
                    ],
                    p=1.0,
                )
            ],
            seed=self.rng.randint(0, sys.maxsize),
        )
        bgr = transform(image=bgr)["image"]

        bitmap = np.concat([bgr, input.bitmap[:, :, 3:4]], axis=2)

        return ImageLayer(
            bitmap=bitmap, dpi=input.dpi, space=input.space, regions=input.regions
        )


class _BackgroundText(Filter):
    """Stamps a short snippet of random text directly onto the paper
    (background) layer, simulating stray handwritten annotations, page
    numbers, or bleed-through text - only meaningful because paper is still
    a separate background layer, painted behind the ink and stafflines."""

    _ALPHABET = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    _FONTS = (
        cv2.FONT_HERSHEY_SIMPLEX,
        cv2.FONT_HERSHEY_COMPLEX,
        cv2.FONT_HERSHEY_DUPLEX,
        cv2.FONT_HERSHEY_SCRIPT_SIMPLEX,
        cv2.FONT_HERSHEY_SCRIPT_COMPLEX,
    )

    def apply_to(self, input: ImageLayer) -> ImageLayer:
        bgr = input.bitmap[:, :, 0:3].copy()
        h, w = bgr.shape[:2]

        text = "".join(
            self.rng.choices(self._ALPHABET, k=self.rng.randint(3, 12))
        )
        font = self.rng.choice(self._FONTS)
        scale = self.rng.uniform(0.4, 1.2)
        thickness = self.rng.randint(1, 2)
        color_val = self.rng.randint(60, 180)

        (text_w, text_h), _ = cv2.getTextSize(text, font, scale, thickness)
        text_w, text_h = max(text_w, 1), max(text_h, 1)
        x = self.rng.randint(0, max(1, w - text_w - 1))
        y = self.rng.randint(text_h + 1, max(text_h + 2, h - 1))

        overlay = np.zeros((h, w), dtype=np.uint8)
        cv2.putText(
            overlay, text, (x, y), font, scale, 255, thickness, cv2.LINE_AA
        )

        angle = self.rng.uniform(-8, 8)
        if abs(angle) > 0.01:
            rot_matrix = cv2.getRotationMatrix2D(
                (x + text_w / 2, y - text_h / 2), angle, 1.0
            )
            overlay = cv2.warpAffine(overlay, rot_matrix, (w, h))

        mask = overlay > 0
        for c in range(3):
            bgr[:, :, c][mask] = color_val

        bitmap = np.concat([bgr, input.bitmap[:, :, 3:4]], axis=2)

        return ImageLayer(
            bitmap=bitmap, dpi=input.dpi, space=input.space, regions=input.regions
        )


class _WeakBlur(Filter):
    """Toned-down replacement for the base pipeline's `_Blur` filter: a
    smaller maximum kernel size and lower trigger probability, so the final
    image stays sharper despite the extra degradations layered on top of it
    by `StrongHandwrittenPostprocessor`."""

    def apply_to(self, input: ImageLayer) -> ImageLayer:
        import albumentations as A

        ksize = max(int(mm_to_px(self.rng.uniform(0.3, 1.2), dpi=input.dpi)), 1)

        transform = A.Compose(
            [A.Blur(blur_limit=ksize, p=1)],
            seed=self.rng.randint(0, sys.maxsize),
        )

        bitmap = transform(image=input.bitmap)["image"]

        return ImageLayer(
            bitmap=bitmap, dpi=input.dpi, space=input.space, regions=input.regions
        )


class _TrackedRotation(Filter):
    """Replacement for the base pipeline's plain-rotation `_Geometric`
    filter: the same small random rotation (with the canvas expanded to fit
    the rotated content, matching PIL's `expand=1`), but also keeps
    `postprocessor.tracked_points` in sync by rotating every tracked point -
    Augraphy's own bounding-box tracking for this filter is too approximate
    to reuse here (see `_rotate_points`)."""

    def __init__(
        self,
        rng: random.Random,
        p: float,
        rotate_range: Tuple[int, int],
        postprocessor: "StrongHandwrittenPostprocessor",
    ) -> None:
        super().__init__(rng, p)
        self.rotate_range = rotate_range
        self.postprocessor = postprocessor

    def apply_to(self, input: ImageLayer) -> ImageLayer:
        from augraphy.augmentations.lib import rotate_image_PIL

        angle = self.rng.randint(*self.rotate_range)
        if angle == 0:
            return input

        h, w = input.bitmap.shape[:2]
        bitmap = rotate_image_PIL(input.bitmap, angle, expand=1)
        rh, rw = bitmap.shape[:2]

        cx, cy = w / 2, h / 2
        x_offset = rw / 2 - cx
        y_offset = rh / 2 - cy

        # rotate_point()/rotate_bounding_boxes() in augraphy use -angle here
        # because PIL rotates the image counter-clockwise for a positive
        # angle
        _rotate_points(
            self.postprocessor.tracked_points, cx, cy, x_offset, y_offset, -angle
        )

        return ImageLayer(
            bitmap=bitmap, dpi=input.dpi, space=input.space, regions=input.regions
        )


class _RandomAffine(Filter):
    """Applies a small random affine warp (rotation, scale, shear,
    translation) to the fully composed page, simulating camera/scan
    perspective jitter beyond the base pipeline's plain rotation."""

    def __init__(
        self,
        rng: random.Random,
        p: float,
        postprocessor: "StrongHandwrittenPostprocessor",
    ) -> None:
        super().__init__(rng, p)
        self.postprocessor = postprocessor

    def apply_to(self, input: ImageLayer) -> ImageLayer:
        h, w = input.bitmap.shape[:2]
        cx, cy = w / 2, h / 2

        angle = self.rng.uniform(-4, 4)
        scale = self.rng.uniform(0.94, 1.06)
        shear_deg = self.rng.uniform(-3, 3)
        tx = self.rng.uniform(-0.02, 0.02) * w
        ty = self.rng.uniform(-0.02, 0.02) * h

        rotation = cv2.getRotationMatrix2D((cx, cy), angle, scale)
        rotation = np.vstack([rotation, [0, 0, 1]])

        shear_rad = np.deg2rad(shear_deg)
        shear = np.array(
            [
                [1, np.tan(shear_rad), -cy * np.tan(shear_rad)],
                [0, 1, 0],
                [0, 0, 1],
            ]
        )

        translation = np.array([[1, 0, tx], [0, 1, ty], [0, 0, 1]])

        matrix = (translation @ shear @ rotation)[:2, :]

        bitmap = cv2.warpAffine(
            input.bitmap,
            matrix,
            (w, h),
            flags=cv2.INTER_LINEAR,
            borderMode=cv2.BORDER_REPLICATE,
        )

        _affine_transform_points(self.postprocessor.tracked_points, matrix)

        return ImageLayer(
            bitmap=bitmap, dpi=input.dpi, space=input.space, regions=input.regions
        )


class StrongHandwrittenPostprocessor(BaseHandwrittenPostprocessor):
    """`BaseHandwrittenPostprocessor` with heavier and more varied
    degradations layered on top, to increase augmentation strength and
    dataset variability:

    - 20% chance of Kanungo-style foreground/background noise
    - 15% chance of a small-kernel foreground dilation/erosion, and an
      independent 7.5% chance of a large-kernel one
    - extra background sensor noise on the paper layer
    - 10% chance of stray background text
    - a small independent ink-layer jitter relative to the staff/paper
    - an extra full-page affine jitter on top of the base rotation

    Point tracking: every filter here that warps geometry (the base
    pipeline's own rotation, this class's ink-layer jitter, and its extra
    full-page affine jitter) also updates `self.tracked_points` in place,
    so a caller that seeds it with the glyphs' pre-postprocessing pixels
    (via `tracked_ink_points`/`tracked_staffline_points`, see
    `generate_smashcima_dataset_strong.py`) gets back points that match the
    final, augmented image. Ink glyphs are seeded with their bbox's 4
    corners (collapsed back into an axis-aligned box by the caller once
    warping is done); stafflines are instead seeded with just their 2
    centerline endpoints and kept as a line segment, never collapsed into a
    box - an axis-aligned box around a rotated line balloons badly, since a
    long thin rectangle's true rotated bbox is a much taller parallelogram.
    The base pipeline's `Folding` filter is instead disabled entirely (see
    `process_final_layer`): its per-band paper-fold warp can't be tracked
    precisely enough to keep points accurate. Small non-geometric filters
    (dilation/erosion, ink median blur) are left untracked, since they only
    nudge a glyph's edges by a few pixels without moving it.
    """

    def __init__(self, rng: random.Random):
        super().__init__(rng)

        # seeded by the caller with the glyphs'/stafflines' pre-
        # postprocessing pixel points before rendering; mutated in place by
        # the tracked filters below as they run
        self.tracked_ink_points: List[PointList] = []
        self.tracked_staffline_points: List[PointList] = []
        self.tracked_points: List[PointList] = []

        self.f_ink_extra = FilterStack(
            [
                _KanungoNoise(rng, p=0.20),
                _ForegroundMorphology(rng, p=0.15, kernel_range=(2, 3)),
                _ForegroundMorphology(rng, p=0.075, kernel_range=(4, 7)),
                _InkLayerJitter(rng, p=0.3, postprocessor=self),
            ],
            rng,
        )

        self.f_paper_extra = FilterStack(
            [
                _PaperNoise(rng, p=0.6),
                _BackgroundText(rng, p=0.10),
            ],
            rng,
        )

        # swaps the base pipeline's plain-rotation `_Geometric` for a
        # box-tracking equivalent (same +/-5deg range), and its `_Blur`
        # (up to 3mm, p=0.5) for a milder one, since the extra degradations
        # added here already reduce sharpness on their own; then adds one
        # more filter (the extra affine jitter, also box-tracking) on top
        self.f_camera.filters[0] = _TrackedRotation(
            rng, p=0.5, rotate_range=(-5, 5), postprocessor=self
        )
        self.f_camera.filters[-1] = _WeakBlur(rng, p=0.3)
        self.f_camera.filters.append(_RandomAffine(rng, p=0.5, postprocessor=self))

    def process_extracted_layers(self, layers: LayerSet) -> LayerSet:
        ink = layers["ink"]
        stafflines = layers["stafflines"]
        paper = layers["paper"]

        # process stafflines (base pipeline's own thickness jitter)
        stafflines = self.f_stafflines(stafflines)

        # process paper (background noise + stray text)
        paper = self.f_paper_extra(paper)

        # process ink: base pipeline's style filters, then our heavier,
        # more varied foreground degradations (including the ink-layer
        # jitter, which may have just moved tracked_ink_points), then
        # base's bleed/color
        ink = self.f_inkstyle(ink)
        ink = self.f_ink_extra(ink)
        ink = self.f_bleed_through(ink)
        ink = self.f_ink_color(ink)

        # the ink jitter above only affects ink glyphs; combine them with
        # the (so far untouched) staffline points into the single list that
        # process_final_layer's tracked filters will keep updating
        self.tracked_points = self.tracked_ink_points + self.tracked_staffline_points

        return LayerSet({"ink": ink, "stafflines": stafflines, "paper": paper})

    def process_final_layer(self, final_layer: ImageLayer) -> ImageLayer:
        final_layer = self.f_scribbles(final_layer)
        # NOTE: the base pipeline's f_folding is intentionally skipped here
        # - see the class docstring
        final_layer = self.f_camera(final_layer)
        return final_layer
